version: '{branch}-{build}'
environment:
  PY_PYTHON: 3.7-32
install:
- cmd: >-
    set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
    python -m pip install -U pip

    python -m pip install wheel

    py -m pip install scons

    py -m pip install markdown

build_script:
- cmd: >-
    scons

    scons pot

artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
- path: '*.pot'
  name: translation
  type: WebDeployPackage
  
before_deploy:
- ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Release $(APPVEYOR_REPO_TAG_NAME)
  description: This is the release $(APPVEYOR_REPO_TAG_NAME) of the $(REPO_NAME) addon for the NVDA screen reader built and uploaded to GitHub using Appveyor.

  auth_token:
    secure: ZFxLKvGeEMn/7/gdTTlDqamDCRofZmGu+cwKQN7PlbX7RlLdTCmLIhPVZbTzGYXL
  artifact: addon
  on:
    appveyor_repo_tag: true

- provider: FTP
  protocol: ftp
  host:
    secure: zlOavGuP/Soxg/BWn/tnCA==
  username:
    secure: KRV5ary404pbCKCCRnNKMQ==
  password:
    secure: HpUOJkphDWfc8nLKU/5Xmw==
  folder: /web/nvda
  artifact: addon
  on:
    appveyor_repo_tag: true

- provider: FTP
  protocol: ftp
  host:
    secure: zlOavGuP/Soxg/BWn/tnCA==
  username:
    secure: KRV5ary404pbCKCCRnNKMQ==
  password:
    secure: HpUOJkphDWfc8nLKU/5Xmw==
  folder: /web/nvda/addons-snapshots
  artifact: addon,translation
  on:
    appveyor_repo_tag: false

